artifacts_root: 
  artifact_root_dir: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_source: data/parkinsons.data
  csv_file_store: artifacts/data

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_source: artifacts/data/parkinsons.csv
  csv_file_store: artifacts/datapreprocessed

model:
  data_source: artifacts/datapreprocessed
  model_store: artifacts/model

model_training:
  data_source: artifacts/datapreprocessed
  model_initial_source: artifacts/model/model.keras
  model_final_source: artifacts/model_final
